# Generated by Django 6.0.3 on 2026-03-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_equipamento_responsavel_and_more'),
        ('rh', '0002_colaborador_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.colaborador', verbose_name='Responsável'),
        ),
    ]
