# Generated by Django 6.0.3 on 2026-03-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_equipamento_responsavel'),
        ('rh', '0002_colaborador_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_responsavel', to='rh.colaborador', verbose_name='Responsável'),
        ),
    ]
