# Generated by Django 6.0.3 on 2026-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_equipamento_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Manutenção'), ('descarte', 'Descartado')], default='disponivel', max_length=20, verbose_name='Status do Equipamento'),
        ),
        migrations.DeleteModel(
            name='Consumivel',
        ),
    ]
