# Generated by Django 6.0.3 on 2026-05-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_equipamento_excluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_equipamentos/galeria/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='estoque.equipamento')),
            ],
        ),
    ]
