# Generated by Django 6.0.3 on 2026-08-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Setor')),
                ('orcamento_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Orçamento Anual')),
            ],
        ),
    ]
