# Generated by Django 6.0.3 on 2026-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Colaborador Ativo?'),
        ),
    ]
