# Generated by Django 6.0.3 on 2026-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_colaborador_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
