# Generated by Django 6.0.3 on 2026-05-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_equipamento_excluido'),
        ('rh', '0004_colaborador_excluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='termos_assinados/', verbose_name='Termo Assinado (PDF)')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_assinados', to='rh.colaborador')),
                ('equipamentos', models.ManyToManyField(related_name='termos', to='estoque.equipamento')),
            ],
        ),
    ]
