# Generated by Django 6.0.3 on 2026-03-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0002_colaborador_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consumivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Item')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('unidade_medida', models.CharField(help_text='Ex: Pacote, Caixa, Unidade, Litro, Kg', max_length=50, verbose_name='Unidade de Medida')),
                ('estoque_minimo', models.IntegerField(default=1, help_text='Quantidade para alertar necessidade de compra', verbose_name='Estoque Mínimo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de Registro')),
                ('nome', models.CharField(max_length=150, verbose_name='Item')),
                ('num_patrimonio', models.CharField(help_text='Número de patrimônio do equipamento', max_length=50, unique=True, verbose_name='Número do Patrimônio')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Manutenção'), ('descarte', 'Descartado')], default='estoque', max_length=20, verbose_name='Status do Equipamento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_equipamentos/', verbose_name='Foto do Equipamento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.categoria')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Responsável')),
                ('validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validador_equipamentos', to='rh.colaborador')),
            ],
        ),
    ]
