# Generated by Django 6.0.3 on 2026-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_equipamento_status_delete_consumivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
