# Generated by Django 6.0.3 on 2026-06-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_equipamentoimagem'),
        ('rh', '0006_departamento_alter_colaborador_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_transferencias', to='estoque.equipamento')),
                ('responsavel_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_anterior', to='rh.colaborador')),
                ('responsavel_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_novo', to='rh.colaborador')),
            ],
        ),
    ]
