# Generated by Django 6.0.3 on 2026-08-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_historicotransferencia'),
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='centro_de_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='patrimonio.centrodecusto', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Compra'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='taxa_depreciacao_anual',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taxa de Depreciação Anual (%)'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor de Compra (R$)'),
        ),
    ]
