# Generated by Django 6.0.3 on 2026-06-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0006_departamento_alter_colaborador_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Use sempre o dia 01 do mês para padronizar. Ex: 2026-06-01', verbose_name='Mês de Referência')),
                ('arquivo_pdf', models.FileField(upload_to='contracheques/%Y/%m/', verbose_name='Arquivo PDF')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Assinatura'), ('assinado', 'Assinado Digitalmente')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracheques', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Contracheque',
                'verbose_name_plural': 'Contracheques',
                'ordering': ['-mes_referencia'],
                'unique_together': {('colaborador', 'mes_referencia')},
            },
        ),
        migrations.CreateModel(
            name='AceiteDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_aceite', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora Exata do Aceite')),
                ('ip_origem', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(verbose_name='Navegador e OS (User Agent)')),
                ('contracheque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aceite_digital', to='folha.contracheque', verbose_name='Contracheque')),
            ],
            options={
                'verbose_name': 'Aceite Digital',
                'verbose_name_plural': 'Aceites Digitais',
            },
        ),
    ]
