# Generated by Django 6.0.3 on 2026-03-24 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('kg', 'Quilo')], default='un', max_length=10)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=5)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoConsumivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra/Reposição)'), ('saida', 'Saída (Consumo/Uso)')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(blank=True, help_text='Para onde foi ou quem pediu?', max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('consumivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='consumiveis.consumivel')),
            ],
        ),
    ]
