# Generated by Django 6.0.3 on 2026-03-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumiveis', '0001_initial'),
        ('rh', '0003_colaborador_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoconsumivel',
            name='destino',
            field=models.CharField(blank=True, help_text='Para onde vai? Ex: Copa 2º Andar, Departamento X', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimentacaoconsumivel',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Quem solicitou ou retirou?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador'),
        ),
    ]
