# Generated by Django 6.0.3 on 2026-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumiveis', '0002_movimentacaoconsumivel_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoconsumivel',
            name='destino',
            field=models.CharField(blank=True, help_text='Para onde vai? Ex: Copa, Departamento X', max_length=100),
        ),
    ]
