# Generated by Django 6.0.3 on 2026-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumiveis', '0003_alter_movimentacaoconsumivel_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumivel',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
